apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: notes-backend
          image: fadillahrizki/notes-backend:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: notes-backend
  ports:
    - port: 3000
      targetPort: 3000
